create table tenants (
    id bigint generated by default as identity primary key,
    slug varchar(80) not null unique,
    name varchar(120) not null,
    queue_open boolean not null default false,
    queue_paused boolean not null default false,
    average_service_minutes integer not null default 30,
    max_queue_size integer not null default 20,
    daily_notice varchar(240),
    whatsapp varchar(30),
    address varchar(180)
);

create table queue_entries (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    customer_name varchar(80) not null,
    phone varchar(25) not null,
    access_token varchar(36) not null unique,
    status varchar(20) not null,
    created_at timestamp with time zone not null,
    called_at timestamp with time zone,
    service_started_at timestamp with time zone,
    finished_at timestamp with time zone
);

create index idx_queue_tenant_status_created on queue_entries(tenant_id, status, created_at);
